[2023-05-05 01:30:08,014] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: postgres_pipeline.query_customers manual__2023-05-05T01:30:06.195269+00:00 [queued]>
[2023-05-05 01:30:08,025] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: postgres_pipeline.query_customers manual__2023-05-05T01:30:06.195269+00:00 [queued]>
[2023-05-05 01:30:08,029] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 01:30:08,031] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-05-05 01:30:08,031] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 01:30:08,047] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): query_customers> on 2023-05-05 01:30:06.195269+00:00
[2023-05-05 01:30:08,051] {standard_task_runner.py:52} INFO - Started process 4802 to run task
[2023-05-05 01:30:08,055] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'query_customers', 'manual__2023-05-05T01:30:06.195269+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/load_from_postgres.py', '--cfg-path', '/tmp/tmp68nw8b9b', '--error-file', '/tmp/tmp4tactqs4']
[2023-05-05 01:30:08,056] {standard_task_runner.py:77} INFO - Job 100: Subtask query_customers
[2023-05-05 01:30:08,140] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_pipeline.query_customers manual__2023-05-05T01:30:06.195269+00:00 [running]> on host ebd7ac88a2d5
[2023-05-05 01:30:08,182] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/xcom.py:323 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:30:08,200] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:126 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:30:08,207] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:162 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-05 01:30:08,219] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:163 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:30:08,224] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_pipeline
AIRFLOW_CTX_TASK_ID=query_customers
AIRFLOW_CTX_EXECUTION_DATE=2023-05-05T01:30:06.195269+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-05T01:30:06.195269+00:00
[2023-05-05 01:30:08,240] {base.py:79} INFO - Using connection to: id: postgres_local. Host: host.docker.internal, Port: 5432, Schema: sample_source_db, Login: ***, Password: ***, extra: {}
[2023-05-05 01:30:08,249] {sql.py:375} INFO - Running statement: SELECT * FROM customers;, parameters: None
[2023-05-05 01:30:08,252] {sql.py:384} INFO - Rows affected: 10
[2023-05-05 01:30:08,287] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=query_customers, execution_date=20230505T013006, start_date=20230505T013008, end_date=20230505T013008
[2023-05-05 01:30:08,307] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-05-05 01:30:08,350] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-05-05 01:30:08,352] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
[2023-05-05 01:30:08,352] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
