[2023-05-05 00:32:40,201] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: postgres_to_localfile.generate_file_name manual__2023-05-05T00:32:38.808431+00:00 [queued]>
[2023-05-05 00:32:40,213] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: postgres_to_localfile.generate_file_name manual__2023-05-05T00:32:38.808431+00:00 [queued]>
[2023-05-05 00:32:40,214] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 00:32:40,214] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-05-05 00:32:40,215] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 00:32:40,227] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): generate_file_name> on 2023-05-05 00:32:38.808431+00:00
[2023-05-05 00:32:40,231] {standard_task_runner.py:52} INFO - Started process 2800 to run task
[2023-05-05 00:32:40,235] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_localfile', 'generate_file_name', 'manual__2023-05-05T00:32:38.808431+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/load_from_postgres.py', '--cfg-path', '/tmp/tmp0qypx860', '--error-file', '/tmp/tmpevrvzvmo']
[2023-05-05 00:32:40,236] {standard_task_runner.py:77} INFO - Job 10: Subtask generate_file_name
[2023-05-05 00:32:40,314] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_to_localfile.generate_file_name manual__2023-05-05T00:32:38.808431+00:00 [running]> on host ebd7ac88a2d5
[2023-05-05 00:32:40,347] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/xcom.py:323 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 00:32:40,361] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:126 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 00:32:40,368] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:162 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-05 00:32:40,378] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:163 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 00:32:40,383] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_to_localfile
AIRFLOW_CTX_TASK_ID=generate_file_name
AIRFLOW_CTX_EXECUTION_DATE=2023-05-05T00:32:38.808431+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-05T00:32:38.808431+00:00
[2023-05-05 00:32:40,383] {python.py:175} INFO - Done. Returned value was: /app/datalake/bronze/load_from_postgres/output_2023-05-05-00-32-40.csv
[2023-05-05 00:32:40,394] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/xcom.py:104 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 00:32:40,420] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=postgres_to_localfile, task_id=generate_file_name, execution_date=20230505T003238, start_date=20230505T003240, end_date=20230505T003240
[2023-05-05 00:32:40,448] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-05-05 00:32:40,491] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-05 00:32:40,492] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
[2023-05-05 00:32:40,493] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
