[2023-05-05 02:53:41,659] {processor.py:163} INFO - Started process (PID=7421) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:53:41,660] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:53:41,661] {logging_mixin.py:109} INFO - [2023-05-05 02:53:41,661] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:53:41,671] {logging_mixin.py:109} INFO - [2023-05-05 02:53:41,669] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 2, in <module>
    from airflow.operators.papermill_operator import PapermillOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/papermill_operator.py", line 22, in <module>
    from airflow.providers.papermill.operators.papermill import PapermillOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.papermill'
[2023-05-05 02:53:41,698] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:53:41,705] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.049 seconds
[2023-05-05 02:54:12,288] {processor.py:163} INFO - Started process (PID=7456) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:54:12,290] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:54:12,291] {logging_mixin.py:109} INFO - [2023-05-05 02:54:12,291] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:54:12,302] {logging_mixin.py:109} INFO - [2023-05-05 02:54:12,300] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 2, in <module>
    from airflow.operators.papermill_operator import PapermillOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/papermill_operator.py", line 22, in <module>
    from airflow.providers.papermill.operators.papermill import PapermillOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.papermill'
[2023-05-05 02:54:12,336] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:54:12,344] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.063 seconds
[2023-05-05 02:54:42,665] {processor.py:163} INFO - Started process (PID=7481) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:54:42,666] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:54:42,666] {logging_mixin.py:109} INFO - [2023-05-05 02:54:42,666] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:54:42,671] {logging_mixin.py:109} INFO - [2023-05-05 02:54:42,670] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 2, in <module>
    from airflow.operators.papermill_operator import PapermillOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/papermill_operator.py", line 22, in <module>
    from airflow.providers.papermill.operators.papermill import PapermillOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.papermill'
[2023-05-05 02:54:42,697] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:54:42,704] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.042 seconds
[2023-05-05 02:55:12,916] {processor.py:163} INFO - Started process (PID=7525) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:55:12,918] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:55:12,918] {logging_mixin.py:109} INFO - [2023-05-05 02:55:12,918] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:55:12,925] {logging_mixin.py:109} INFO - [2023-05-05 02:55:12,924] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 2, in <module>
    from airflow.operators.papermill_operator import PapermillOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/papermill_operator.py", line 22, in <module>
    from airflow.providers.papermill.operators.papermill import PapermillOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.papermill'
[2023-05-05 02:55:12,958] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:55:12,971] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.059 seconds
[2023-05-05 02:55:43,225] {processor.py:163} INFO - Started process (PID=7557) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:55:43,227] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:55:43,228] {logging_mixin.py:109} INFO - [2023-05-05 02:55:43,228] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:55:43,236] {logging_mixin.py:109} INFO - [2023-05-05 02:55:43,234] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 2, in <module>
    from airflow.operators.papermill_operator import PapermillOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/papermill_operator.py", line 22, in <module>
    from airflow.providers.papermill.operators.papermill import PapermillOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.papermill'
[2023-05-05 02:55:43,275] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:55:43,288] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.067 seconds
[2023-05-05 02:56:13,548] {processor.py:163} INFO - Started process (PID=7591) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:56:13,551] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:56:13,552] {logging_mixin.py:109} INFO - [2023-05-05 02:56:13,552] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:56:13,922] {logging_mixin.py:109} INFO - [2023-05-05 02:56:13,921] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    org_mod_name, _ = os.path.splitext(os.path.split(filepath)[-1])
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 10, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-05-05 02:56:13,958] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:56:13,968] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.427 seconds
[2023-05-05 02:56:44,094] {processor.py:163} INFO - Started process (PID=7617) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:56:44,097] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:56:44,098] {logging_mixin.py:109} INFO - [2023-05-05 02:56:44,098] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:56:44,426] {logging_mixin.py:109} INFO - [2023-05-05 02:56:44,425] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    org_mod_name, _ = os.path.splitext(os.path.split(filepath)[-1])
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 10, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-05-05 02:56:44,449] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:56:44,455] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.366 seconds
[2023-05-05 02:57:59,116] {processor.py:163} INFO - Started process (PID=170) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:57:59,117] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:57:59,117] {logging_mixin.py:109} INFO - [2023-05-05 02:57:59,117] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:57:59,122] {logging_mixin.py:109} INFO - [2023-05-05 02:57:59,121] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 2, in <module>
    from airflow.operators.papermill_operator import PapermillOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/papermill_operator.py", line 22, in <module>
    from airflow.providers.papermill.operators.papermill import PapermillOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.papermill'
[2023-05-05 02:57:59,147] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:57:59,175] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.061 seconds
[2023-05-05 02:58:29,464] {processor.py:163} INFO - Started process (PID=194) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:58:29,465] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:58:29,466] {logging_mixin.py:109} INFO - [2023-05-05 02:58:29,466] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:58:29,472] {logging_mixin.py:109} INFO - [2023-05-05 02:58:29,471] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 2, in <module>
    from airflow.operators.papermill_operator import PapermillOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/papermill_operator.py", line 22, in <module>
    from airflow.providers.papermill.operators.papermill import PapermillOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.papermill'
[2023-05-05 02:58:29,500] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:58:29,508] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.048 seconds
[2023-05-05 02:58:59,902] {processor.py:163} INFO - Started process (PID=220) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:58:59,903] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:58:59,904] {logging_mixin.py:109} INFO - [2023-05-05 02:58:59,904] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:58:59,910] {logging_mixin.py:109} INFO - [2023-05-05 02:58:59,909] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 2, in <module>
    from airflow.operators.papermill_operator import PapermillOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/papermill_operator.py", line 22, in <module>
    from airflow.providers.papermill.operators.papermill import PapermillOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.papermill'
[2023-05-05 02:58:59,940] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:58:59,948] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.049 seconds
[2023-05-05 02:59:30,334] {processor.py:163} INFO - Started process (PID=240) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 02:59:30,336] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 02:59:30,337] {logging_mixin.py:109} INFO - [2023-05-05 02:59:30,337] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:59:30,345] {logging_mixin.py:109} INFO - [2023-05-05 02:59:30,343] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 2, in <module>
    from airflow.operators.papermill_operator import PapermillOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/papermill_operator.py", line 22, in <module>
    from airflow.providers.papermill.operators.papermill import PapermillOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.papermill'
[2023-05-05 02:59:30,385] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 02:59:30,397] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.066 seconds
[2023-05-05 03:00:00,705] {processor.py:163} INFO - Started process (PID=260) to work on /app/airflow/dags/sample_papermill.py
[2023-05-05 03:00:00,706] {processor.py:642} INFO - Processing file /app/airflow/dags/sample_papermill.py for tasks to queue
[2023-05-05 03:00:00,707] {logging_mixin.py:109} INFO - [2023-05-05 03:00:00,707] {dagbag.py:500} INFO - Filling up the DagBag from /app/airflow/dags/sample_papermill.py
[2023-05-05 03:00:00,714] {logging_mixin.py:109} INFO - [2023-05-05 03:00:00,713] {dagbag.py:334} ERROR - Failed to import: /app/airflow/dags/sample_papermill.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/sample_papermill.py", line 2, in <module>
    from airflow.operators.papermill_operator import PapermillOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/papermill_operator.py", line 22, in <module>
    from airflow.providers.papermill.operators.papermill import PapermillOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.papermill'
[2023-05-05 03:00:00,747] {processor.py:656} WARNING - No viable dags retrieved from /app/airflow/dags/sample_papermill.py
[2023-05-05 03:00:00,757] {processor.py:171} INFO - Processing /app/airflow/dags/sample_papermill.py took 0.054 seconds
